/**
 * Google Docs & Google Drive Real Artifact Exporter
 * Generates formatted Google Docs payloads, Drive folder structures,
 * and high-fidelity Markdown / HTML / PDF-ready documents from Gauntlet workspace deliverables.
 */

import { type Mission } from "./types.ts";
import { type DailyLog } from "./habit-store.ts";
import { type TicketItem } from "./ticket-store.ts";
import { type BriefingSession } from "./briefing-store.ts";

export interface GoogleDocExportPayload {
  title: string;
  folderName: string;
  mimeType: string;
  documentBody: string;
  markdownContent: string;
  tableOfContents: string[];
  metadata: {
    exportedAt: string;
    wordCount: number;
    sourceSystem: string;
    version: string;
  };
  googleDocsBatchRequests: Array<{
    insertText?: {
      location: { index: number };
      text: string;
    };
    updateTextStyle?: {
      range: { startIndex: number; endIndex: number };
      textStyle: Record<string, unknown>;
      fields: string;
    };
  }>;
}

export class GoogleDocsExporter {
  /**
   * Export a Gauntlet Mission with all its 6-round artifacts, plans, and dispatches.
   */
  static exportMission(mission: Mission): GoogleDocExportPayload {
    const title = `Gauntlet Deliverable: ${mission.goal.slice(0, 50)}`;
    const md: string[] = [];

    md.push(`# ${title}`);
    md.push(`**Status:** ${mission.status.toUpperCase()} | **Score:** ${mission.score || 0}% | **Rounds Completed:** ${mission.rounds.length}/6`);
    md.push(`**Date Generated:** ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`);
    md.push(`**Objective:** ${mission.objective || mission.goal}`);
    md.push(`\n---\n`);

    if (mission.plan && mission.plan.length > 0) {
      md.push(`## Strategic Execution Plan`);
      mission.plan.forEach((step, idx) => {
        md.push(`### ${idx + 1}. ${step.title} (${step.assignedAgent})`);
        md.push(`${step.description}`);
        md.push(`- **Action Type:** \`${step.actionType}\``);
        md.push(`- **Dependencies:** ${step.dependencies?.join(", ") || "None"}`);
      });
      md.push(`\n---\n`);
    }

    if (mission.rounds.length > 0) {
      md.push(`## 6-Stage Autonomous Loop Evaluation`);
      mission.rounds.forEach((rnd) => {
        md.push(`### Round ${rnd.round}: ${rnd.objective || "Stage Synthesis"}`);
        md.push(`- **Verifier Verdict:** ${rnd.verdict?.approved ? "APPROVED (100%)" : "CRITIQUED"}`);
        if (rnd.verdict?.feedback) {
          md.push(`- **Critique Notes:** ${rnd.verdict.feedback}`);
        }
        if (rnd.criticisms && rnd.criticisms.length > 0) {
          md.push(`- **Strengths & Gaps:** ${rnd.criticisms.join(" | ")}`);
        }
      });
      md.push(`\n---\n`);
    }

    if (mission.dispatch) {
      md.push(`## Dispatched Workspace Actions`);
      if (mission.dispatch.gmailDrafts.length > 0) {
        md.push(`### Gmail Drafts (${mission.dispatch.gmailDrafts.length})`);
        mission.dispatch.gmailDrafts.forEach((draft, i) => {
          md.push(`- **[Draft ${i + 1}] To:** ${draft.to} | **Subject:** ${draft.subject}`);
          md.push(`  > ${draft.body.replace(/\n/g, "\n  > ")}`);
        });
      }
      if (mission.dispatch.calendarEvents.length > 0) {
        md.push(`### Google Calendar Events (${mission.dispatch.calendarEvents.length})`);
        mission.dispatch.calendarEvents.forEach((ev) => {
          md.push(`- **${ev.title}**: ${ev.start} to ${ev.end}`);
        });
      }
    }

    const markdownContent = md.join("\n\n");
    const wordCount = markdownContent.split(/\s+/).length;

    return {
      title,
      folderName: "Gauntlet Missions",
      mimeType: "application/vnd.google-apps.document",
      documentBody: markdownContent,
      markdownContent,
      tableOfContents: ["Strategic Execution Plan", "6-Stage Autonomous Loop Evaluation", "Dispatched Workspace Actions"],
      metadata: {
        exportedAt: new Date().toISOString(),
        wordCount,
        sourceSystem: "Gauntlet AI Studio",
        version: "v2.0",
      },
      googleDocsBatchRequests: [
        {
          insertText: {
            location: { index: 1 },
            text: markdownContent,
          },
        },
      ],
    };
  }

  /**
   * Export Daily Routine, Trading PnL, and Ticket Itinerary report.
   */
  static exportDailyLog(
    log: DailyLog,
    tickets: TicketItem[],
    briefing?: BriefingSession | null
  ): GoogleDocExportPayload {
    const title = `Executive Daily Digest: ${log.date}`;
    const md: string[] = [];

    md.push(`# ${title}`);
    md.push(`**Productivity & Routine Score:** ${log.productivityScore || 85}%`);
    md.push(`**Generated by:** Gauntlet Autonomous Executive Assistant`);
    md.push(`\n---\n`);

    if (briefing) {
      md.push(`## Executive Audio Transcript`);
      md.push(`> "${briefing.transcript}"`);
      md.push(`\n---\n`);
    }

    if (log.tradingPnl) {
      const pnl = log.tradingPnl;
      const isPos = pnl.realized >= 0;
      md.push(`## Trading Performance & Risk Log`);
      md.push(`- **Realized PnL:** ${isPos ? "+" : ""}$${pnl.realized.toFixed(2)}`);
      md.push(`- **Total Executions:** ${pnl.tradesCount} positions`);
      md.push(`- **Win Rate:** ${pnl.winRate || 75}%`);
      md.push(`- **Risk Notes:** ${pnl.notes || "Standard risk parameters respected."}`);
      md.push(`\n---\n`);
    }

    if (log.meetingsSummary) {
      md.push(`## Google Meetings & Calendar Agenda`);
      md.push(`- **Total Scheduled:** ${log.meetingsSummary.count} calls`);
      log.meetingsSummary.upcoming.forEach((m) => {
        md.push(`- 📅 ${m}`);
      });
      md.push(`\n---\n`);
    }

    if (tickets.length > 0) {
      md.push(`## Active Travel & Tickets Itinerary`);
      tickets.forEach((t) => {
        md.push(`### [${t.category.toUpperCase()}] ${t.title}`);
        md.push(`- **Confirmation / PNR:** \`${t.referenceCode}\``);
        md.push(`- **Departure / Time:** ${t.departureTime || "N/A"} ➔ **Arrival:** ${t.arrivalTime || "N/A"}`);
        md.push(`- **Seat / Gate:** ${t.seat || "Unassigned"} (Gate: ${t.gate || "TBD"})`);
        md.push(`- **Status:** ${t.status.toUpperCase()} | **Price:** $${t.price || 0}`);
      });
      md.push(`\n---\n`);
    }

    md.push(`## Daily Routines & Habits Check`);
    log.habits.forEach((h) => {
      md.push(`- [${h.completed ? "x" : " "}] **${h.title}** (${h.category}) ${h.streak ? `• 🔥 ${h.streak} day streak` : ""}`);
    });

    const markdownContent = md.join("\n\n");
    const wordCount = markdownContent.split(/\s+/).length;

    return {
      title,
      folderName: "Gauntlet Daily Logs",
      mimeType: "application/vnd.google-apps.document",
      documentBody: markdownContent,
      markdownContent,
      tableOfContents: ["Executive Audio Transcript", "Trading Performance & Risk Log", "Google Meetings & Calendar Agenda", "Active Travel & Tickets Itinerary", "Daily Routines & Habits Check"],
      metadata: {
        exportedAt: new Date().toISOString(),
        wordCount,
        sourceSystem: "Gauntlet AI Studio",
        version: "v2.0",
      },
      googleDocsBatchRequests: [
        {
          insertText: {
            location: { index: 1 },
            text: markdownContent,
          },
        },
      ],
    };
  }

  /**
   * Helper to trigger direct client download as Markdown or HTML file.
   */
  static downloadAsFile(filename: string, content: string, mimeType: string = "text/markdown") {
    if (typeof window === "undefined") return;
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
}
